name: Create GitHub Release

on:
  workflow_call:
    inputs:
      artifacts_pattern:
        description: "Ruta de los archivos a subir al release"
        required: false
        default: "**/*"
        type: string
      artifacts_name:
        description: "Nombre del artefacto"
        required: false
        default: ""
        type: string
      environment:
        description: "Nombre del entorno (dev, homo, prod)"
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: artifacts      # Nombre del artifact
          path: ./

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: |
            Release generado automáticamente en el ambiente ${{ inputs.environment }}.
            Artefacto: `${{ inputs.artifacts_name }}`
            Subido a GitHub Release por pipeline `${{ github.workflow }}`.
          files: ${{ inputs.artifacts_pattern }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
