name: Create GitHub Release

on:
  workflow_call:
    inputs:
      artifacts_pattern:
        description: "Ruta de los archivos a subir al release"
        required: false
        default: "**/*"
        type: string
      artifacts_name:
        description: "Nombre del artefacto"
        required: false
        default: ""
        type: string
      environment:
        description: "Nombre del entorno (dev, homo, prod)"
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Obtener run-id del último workflow exitoso desde un pull request
        id: get_run_id
        run: |
          run_id=$(gh api "repos/${{ github.repository }}/actions/workflows/ci.yml/runs?status=success&event=pull_request&per_page=1" --jq '.workflow_runs[0].id')
          echo "run-id=$run_id" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          workflow: ${{ inputs.source_workflow }}  # Nombre del workflow que generó el artifact
          name: artifacts      # Nombre del artifact
          run-id: ${{ steps.get_run_id.outputs.run-id }}
          path: ./

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: |
            Release generado automáticamente en el ambiente ${{ inputs.environment }}.
            Artefacto: `${{ inputs.artifacts_name }}`
            Subido a GitHub Release por pipeline `${{ github.workflow }}`.
            Workflow origen: `${{ inputs.source_workflow }}`.
          files: ${{ inputs.artifacts_pattern }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
