name: Deploy to WebLogic

on:
  workflow_call:
    inputs:
      artifacts_pattern:
        description: 'Directorio o expresión regular que describe qué se desea almacenar como artefacto'
        required: true
        default: 'build/ear/*ear'
        type: string
      artifacts_name:
        description: 'Nombre del Ear'
        required: true
        default: 'HelloWorld'
        type: string
      server_host:
        description: "URL o IP del servidor WebLogic"
        required: true
        type: string
      server_port:
        description: "Puerto del servidor WebLogic"
        required: true
        type: string
      weblogic_user:
        description: "Usuario con permisos de despliegue"
        required: true
        type: string
      target_name:
        description: "Nombre del target (server, cluster, etc.)"
        required: true
        type: string
      app_name:
        description: "Nombre lógico de la aplicación"
        required: true
        type: string
      environment:
        description: "Nombre del entorno GitHub (dev, homo, prod)"
        required: true
        type: string
    #secrets:
      #WEBLOGIC_PASSWORD:
        #description: "Password del usuario WebLogic"
        #required: true

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: ear-and-classes-artifact
          path: downloaded-ear

      - name: Verificar artefacto
        run: |
          echo "Buscando EAR en downloaded-ear/..."
          find downloaded-ear/ -type f -name '*.ear' -exec ls -lh {} \;
      
      - name: (Test) Desplegar a WebLogic
        run: |
          echo "Desplegando ${inputs.artifacts_name} a ${inputs.server_host}:${inputs.server_port}"