name: Deploy to WebLogic

on:
  workflow_call:
    inputs:
      artifacts_name:
        description: 'Nombre del Ear'
        required: true
        default: 'HelloWorld'
        type: string
      server_host:
        description: "URL o IP del servidor WebLogic"
        required: true
        type: string
      server_port:
        description: "Puerto del servidor WebLogic"
        required: true
        type: string
      weblogic_user:
        description: "Usuario con permisos de despliegue"
        required: true
        type: string
      target_name:
        description: "Nombre del target (server, cluster, etc.)"
        required: true
        type: string
      app_name:
        description: "Nombre lógico de la aplicación"
        required: true
        type: string
      environment:
        description: "Nombre del entorno GitHub (dev, homo, prod)"
        required: true
        type: string
      release_tag:
        description: "Tag del release a descargar"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:

      - name: Descargar release con tag
        if: ${{ inputs.environment != 'desarrollo' }}
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: ${{ inputs.release_tag }}
          fileName: "*.ear"
          out-file-path: "deployment-files"

      - name: Descargar artifact desde workflow
        if: ${{ inputs.environment == 'desarrollo' }}
        uses: actions/download-artifact@v4
        with:
          name: ear-and-classes-artifact
          path: deployment-files

      - name: Verificar archivos
        run: |
          echo "Contenido de deployment-files/:"
          ls -lh deployment-files/
          echo "Archivo EAR encontrado:"
          find deployment-files/ -type f -name '*.ear' -exec ls -lh {} \;

      - name: Mostrar release tag
        if: ${{ inputs.environment != 'desarrollo' }}
        run: 'echo "Release: ${{ inputs.release_tag }}"'

      - name: (Test) Desplegar a WebLogic 
        run: |
          EAR_PATH=$(find deployment-files/ -type f -name '*.ear' | head -n1)
          echo "Desplegando [$EAR_PATH] a ${{ inputs.server_host }}:${{ inputs.server_port }}"

      - name: Notificar despliegue exitoso
        if: ${{ inputs.environment != 'desarrollo' }}
        run: 'echo "::notice title=Release Desplegado::Versión: ${{ inputs.release_tag }}%0AAmbiente: ${{ inputs.environment }}"'
